name: Context testing
on: push

jobs:
  Before:
    runs-on: ubuntu-latest
    outputs:
      svcname: ${{ steps.convert_repo_to_fqdn.outputs.svcname }}
      svcname2: ${{ steps.testing_output.outputs.svcname }}
    steps:
      - id: convert_repo_to_fqdn
        name: Get repo convert to FQDN
        run: |
          SVCNAME=$(echo ${{ github.repository }} | sed 's|${{ github.repository_owner }}/||g' | sed 's|_|-|g' | sed 's|[A-Z][a-z]|-&|g' | sed 's|[A-Z][A-Z]\+|-&|g' | tr 'A-Z' 'a-z' | sed 's|^-||g')
          echo "::set-output name=svcname::${SVCNAME}"
      - id: testing_output
        name: Testing OUTPUT
        run: echo "::set-output name=svcname::private"

  Baking:
    runs-on: ubuntu-latest
    needs: [Before]
    steps:
      - name: display svcname
        run: | 
          echo value1 ${{ needs.Before.outputs.svcname }}
          echo value2 ${{ needs.Before.outputs.svcname2 }}