name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: call another action
        uses: mammdoo/actions-demo-composite@main
