name: Context testing
on: push

jobs:
  Before:
    name: script for before 
    runs-on: ubuntu-latest
    outputs:
      svcname: ${{ steps.convert_repo_to_fqdn.outputs.svcname }}
    steps:
      - id: convert_repo_to_fqdn
        name: Get repo convert to FQDN
        run: |
          echo '::set-output name=svcname::value1'
      - name: print repo name
        run: |
          SVCNAME=$(echo ${{ github.repository }} | sed 's|${{ github.repository_owner }}/||g' | sed 's|_|-|g' | sed 's|[A-Z][a-z]|-&|g' | sed 's|[A-Z][A-Z]\+|-&|g' | tr 'A-Z' 'a-z' | sed 's|^-||g')
          echo $SVCNAME

  Baking:
    runs-on: ubuntu-latest
    needs: [Before]
    steps:
      - name: display svcname
        run: | 
          echo value1 ${{ needs.Before.outputs.svcnname }}
