name: Mammdoo unified workflow
run-name: Unified standlone workflow
on: [push]
jobs:
  Baking:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Docker | login | aliyun
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REGISTRY_ALI_USERNAME }}
          password: ${{ secrets.REGISTRY_ALI_PASSWORD }}
      - 
        name: Docker | login | main
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_MAIN_USERNAME }}
          password: ${{ secrets.REGISTRY_MAIN_PASSWORD }}
